// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-qiUPAdnaofZD8YnK8Wt0YN41RolkUE',
    appId: '1:455200024079:web:66681d7167fa8db8d2257a',
    messagingSenderId: '455200024079',
    projectId: 'iotsensordb-9b204',
    authDomain: 'iotsensordb-9b204.firebaseapp.com',
    databaseURL: 'https://iotsensordb-9b204-default-rtdb.firebaseio.com',
    storageBucket: 'iotsensordb-9b204.appspot.com',
    measurementId: 'G-QXJVRFTFES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7cYOZKVf6x3wWDbHe7ZKN-TBj2LQH7A',
    appId: '1:455200024079:android:75f0cd924b8323a4d2257a',
    messagingSenderId: '455200024079',
    projectId: 'iotsensordb-9b204',
    databaseURL: 'https://iotsensordb-9b204-default-rtdb.firebaseio.com',
    storageBucket: 'iotsensordb-9b204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoeF-xGG57-0LEvgi92A6q8vfBv2s2w8',
    appId: '1:455200024079:ios:649b2303352f86c3d2257a',
    messagingSenderId: '455200024079',
    projectId: 'iotsensordb-9b204',
    databaseURL: 'https://iotsensordb-9b204-default-rtdb.firebaseio.com',
    storageBucket: 'iotsensordb-9b204.appspot.com',
    androidClientId: '455200024079-4t45fnc0s9903lsrs4vk68uqlvnqpi8s.apps.googleusercontent.com',
    iosClientId: '455200024079-0608kdv41u7hb14svelb182virg7dlja.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotqueryfetch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoeF-xGG57-0LEvgi92A6q8vfBv2s2w8',
    appId: '1:455200024079:ios:649b2303352f86c3d2257a',
    messagingSenderId: '455200024079',
    projectId: 'iotsensordb-9b204',
    databaseURL: 'https://iotsensordb-9b204-default-rtdb.firebaseio.com',
    storageBucket: 'iotsensordb-9b204.appspot.com',
    androidClientId: '455200024079-4t45fnc0s9903lsrs4vk68uqlvnqpi8s.apps.googleusercontent.com',
    iosClientId: '455200024079-0608kdv41u7hb14svelb182virg7dlja.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotqueryfetch',
  );
}
